# Copyright (c) 21.01.23 18:57 Kilian Schulz
#
# See file LICENSE for information

# This file is the config file for i3guesstemator.

writer: i3bar
updateInterval: 1000                    # in ms

generatorList: [battery,ram,cpu,time]

i3bar:
  useColor: true
  neutralColor: [255, 255, 255]
  positiveColor: [0, 255, 0]
  negativeColor: [255, 0, 0]