# Copyright (c) 21.01.23 18:57 Kilian Schulz
#
# See file LICENSE for information

# This file is the config file for i3guesstemator.

writer: i3bar
updateInterval: 1000                    # in ms

generatorList: [ disk,ram,cpu,time ]

disk:
  prefix: "\uf1c0   "
  paths: ["/", "/home"]

battery:
  prefix: "\uf242   "
  path: "/sys/class/power_supply/BAT0/uevent"
  numIntervals: 300

ram:
  prefix: "\uf00a   "

cpu:
  prefix: "\uf2db   "

brightness:
  prefix: "\uf0eb   "

time:
  prefix: "\uf017   "

i3bar:
  useColor: true
  neutralColor: [ 255, 255, 255 ]
  positiveColor: [ 0, 255, 0 ]
  negativeColor: [ 255, 0, 0 ]
